export const Users = [
  {
    id: 1,
    first_name: "Emiline",
    last_name: "McClune",
    last_os: "Windows 11",
    email: "emcclune0@xrea.com",
    gender: "Female",
  },
  {
    id: 2,
    first_name: "Felix",
    last_name: "Ingleston",
    last_os: "Windows 11",
    email: "fingleston1@hibu.com",
    gender: "Female",
  },
  {
    id: 3,
    first_name: "Travus",
    last_name: "Bergstram",
    last_os: "Windows 11",
    email: "tbergstram2@pbs.org",
    gender: "Female",
  },
  {
    id: 4,
    first_name: "Hollyan",
    last_name: "Knighton",
    last_os: "Windows 11",
    email: "hknighton3@pbs.com",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Sollie",
    last_name: "Naultyiesy",
    last_os: "Windows 11",
    email: "snaulty4897@pbs.com",
    gender: "Male",
  },
  {
    id: 6,
    first_name: "Annie",
    last_name: "Cockayme",
    last_os: "Windows 11",
    email: "acockayme5@pbs.com",
    gender: "Male",
  },
];
